key1=jdbc:sqlserver:/DBSRV02:1433;databaseName=EdmDb_2008_001;user=PDMUser;password=PDMUser;encrypt=false;trustServerCertificate=false;loginTimeout=30;
key2=jdbc:sqlserver://DBSRV02:1433;databaseName=bomb_Confine;user=adhoc;password=adhoc;encrypt=false;trustServerCertificate=false;loginTimeout=30;
;user=PDMUser
;psw=PDMUser
