-- Database Section
-- ________________ 
DROP DATABASE IF EXISTS DesFusion;

CREATE DATABASE DesFusion;
USE DesFusion;

-- DBSpace Section
-- _______________

-- Tables Section
-- _____________ 

CREATE TABLE DESCRIZIONIGRUPPI (
     Id INT NOT NULL AUTO_INCREMENT,
     DESCRIZIONE VARCHAR(80) NOT NULL,
     INGLESE VARCHAR(80) NOT NULL,
     Gruppo VARCHAR(80) NOT NULL,     
     PRIMARY KEY (Id),
     CONSTRAINT des_desIng_grup UNIQUE (Descrizione, INGLESE, Gruppo)
     );
     
CREATE TABLE PRINTHISTORY(
	Id INT NOT NULL AUTO_INCREMENT,
	codCodice VARCHAR(80) NOT NULL, 
     cpNome VARCHAR(80) NOT NULL,
     propValore VARCHAR(80) NOT NULL,
     startValue DATE NOT NULL,
     endValue DATE NOT NULL,
     PRIMARY KEY (Id)
     );
     
CREATE TABLE PrintPropValue(
	Id INT NOT NULL AUTO_INCREMENT,
	 codCodice VARCHAR(80) NOT NULL, 
     cpNome VARCHAR(80) NOT NULL,
     propValore VARCHAR(80) NOT NULL,
     PRIMARY KEY (Id)
     );

-- Index Section
-- _____________ 

CREATE UNIQUE INDEX ID_DESCRIZIONI
     ON DESCRIZIONIGRUPPI (Id);
    
-- Views Section
-- _____________


-- Insertions Section
-- _____________ 

INSERT INTO DESCRIZIONIGRUPPI (Gruppo , DESCRIZIONE, INGLESE) VALUES
('AFF_ANELLI FISSAGGIO CONI VIBRANTI', '',  ''),
('CDS_COCLEE DISTRIBUTRICI E ACCESSORI', 'ALBERO SUPPORTO WAM', 'WAM SUPPORT SHAFT'),
('CMV_COCLEE MESCOLATRICI VERTICALI', 'LAMIERA TELAIO SOSTEGNO DISSIPATORE SU FILTRO', 'SUPPORTING SHEET METAL FRAME FOR THE HEAT SINK ON THE FILTER'),
('CUR_CURVE AMPIO RAGGIO E SALDATE', 'CURVA 90° A MANDRINARE', 'CURVE BENT TO 90° TO EXPAND'),
('EST_ESTRAZIONE SU STELLARE', 'COLLEGAMENTO A STELLARE 11L DI LINEA DA CONO RIGIDO', 'CONNECTION TO 11L LINE STELLAR VALVE FROM RIGID CONE'),
('FAP_FILTRI AUTOPULENTI', 'ASPIRATORE CON ATTACCHI A PARETE', 'ASPIRATOR WITH WALL CONNECTIONS'),
('FOL_FONDI BOMBATI LAVORATI', 'CONO VIBRANTE 2 USCITE CENTRALI 4 BIELLE', 'VIBRATING CONE WITH 2 CENTRAL OUTLETS 4 CONNECTING RODS'),
('IMP_IMPIANTI COMPLETI', 'KIT VIBRATORE TRAMOGGIA', 'HOPPER VIBRATOR KIT'),
('MCC_MICROCOPACT', '',  ''),
('MNC_MINICOTTI PER TUBAZIONI', 'COLLARE DI GIUNZIONE TUBAZIONE', 'JOINING COLLAR FOR PIPE'),
('PST_PRESSOSTATI E ACCESSORI', 'PRESSOSTATO MECCANICO ASSEMBLATO', 'ASSEMBLED MECHANICAL PRESSURE SWITCH'),
('RIP_RIPARAZIONE', '',  ''),
('RIT_RINFORZI TUBOLARI PER SBL', '',  ''),
('RIT_RINFORZI TUBOLARI PER SBL', 'PIATTO ASOLATO', 'SLOTTED PLATE'),
('RIT_RINFORZI TUBOLARI PER SBL', 'PUTRELLA', 'BEAM'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO A PARETE', 'WALL REINFORCEMENT'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO DESTRO PANNELLO SOPRA PIEDE', 'RIGHT REINFORCEMENT PANEL ABOVE FOOT'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO DESTRO PANNELLO SOPRA PIEDE MI', 'RIGHT REINFORCEMENT PANEL ABOVE FOOT MI'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO PANNELLO SOPRA PIEDE', 'REINFORCEMENT PANEL ABOVE FOOT'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO SINISTRO PANNELLO SOPRA PIEDE', 'LEFT REINFORCEMENT PANEL ABOVE FOOT'),
('RIT_RINFORZI TUBOLARI PER SBL', 'RINFORZO SINISTRO PANNELLO SOPRA PIEDE MI', 'LEFT REINFORCEMENT PANEL ABOVE FOOT MI'),
('RIT_RINFORZI TUBOLARI PER SBL', 'TUBOLARE', 'TUBULAR'),
('RIZ_RINFORZI A Z', '',  ''),
('RIZ_RINFORZI A Z', 'RINFORZO ORIZZONTALE A Z', 'HORIZONTAL Z-SHAPED REINFORCEMENT'),
('RIZ_RINFORZI A Z', 'RINFORZO VERTICALE A Z', 'VERTICAL Z-SHAPED REINFORCEMENT'),
('ROB_RINFORZI OBLO SILBOX', '',  ''),
('ROB_RINFORZI OBLO SILBOX', 'RINFORZO OBLO', 'PORTHOLE REINFORCEMENT'),
('RPA_RINFORZI PARETI SILBOX', '',  ''),
('RPA_RINFORZI PARETI SILBOX', 'RINFORZO A PARETE', 'WALL REINFORCEMENT'),
('RPR_RIDUTTORI DI PRESSIONE', '',  ''),
('RPR_RIDUTTORI DI PRESSIONE', 'GHIERA', 'RING'),
('RPR_RIDUTTORI DI PRESSIONE', 'KIT RIDUTTORI DI PRESSIONE', 'PRESSURE REDUCER KIT'),
('RPR_RIDUTTORI DI PRESSIONE', 'LAMIERA FISSAGGIO RIDUTTORE', 'FIXING SHEET METAL FOR REDUCER'),
('RPR_RIDUTTORI DI PRESSIONE', 'RIDUTTORE DI PRESSIONE', 'PRESSURE REDUCER'),
('RPR_RIDUTTORI DI PRESSIONE', 'VALVOLA DI SICUREZZA PER ACQUA', 'WATER SAFETY VALVE'),
('RSB_RINVII ANGOLARI', '',  ''),
('RSB_RINVII ANGOLARI', 'RINVIO ANGOLARE', 'ANGULAR RETURN'),
('RST_RESISTENZE ELETTRICHE', '',  ''),
('RST_RESISTENZE ELETTRICHE', 'PROTEZIONE RESISTENZA', 'RESISTANCE PROTECTION'),
('RST_RESISTENZE ELETTRICHE', 'REGGIA', 'STRAP'),
('RST_RESISTENZE ELETTRICHE', 'RESISTENZA ELETTRICA', 'ELECTRICAL RESISTANCE'),
('RST_RESISTENZE ELETTRICHE', 'RISCALDATORE', 'HEATER'),
('RST_RESISTENZE ELETTRICHE', 'TERMOMETRO', 'THERMOMETER'),
('RST_RESISTENZE ELETTRICHE', 'TERMOSTATO CON GUAINA', 'THERMOSTAT WITH SHEATH'),
('RST_RESISTENZE ELETTRICHE', 'TUBO CON RESISTENZA ELETTRICA', 'PIPE WITH ELECTRIC RESISTANCE'),
('RTE_RINFORZI TETTI SILBOX', '',  ''),
('RTE_RINFORZI TETTI SILBOX', 'RINFORZO TETTO', 'ROOF REINFORCEMENT'),
('RTP_RACCORDO TRE PEZZI OTTONE', '',  ''),
('RTP_RACCORDO TRE PEZZI OTTONE', 'RACCORDO TRE PEZZI', 'THREE-PIECE FITTING'),
('RTT_RINFORZI TETTO SILBOX', '',  ''),
('RTT_RINFORZI TETTO SILBOX', 'RINFORZO TETTO SBL', 'ROOF REINFORCEMENT FOR SBL'),
('RTT_RINFORZI TETTO SILBOX', 'RINFORZO TETTO SBX', 'ROOF REINFORCEMENT FOR SBLX'),
('SAD_SISTEMA ANTIDEPRESSIONE', '',  ''),
('SAD_SISTEMA ANTIDEPRESSIONE', 'ANTIVIBRANTE BIELLA', 'ANTI-VIBRATION FOR CONNECTING ROD'),
('SAD_SISTEMA ANTIDEPRESSIONE', 'BIELLA DI SICUREZZA', 'SAFETY CONNECTING ROD'),
('SAD_SISTEMA ANTIDEPRESSIONE', 'BIELLA DI SICUREZZA CON ANTIVIBRANTI', 'SAFETY CONNECTING ROD WITH VIBRATION DAMPERS');
INSERT INTO PrintPropValue(codCodice ,cpNome,propValore) VALUE
('AFF06520','Officina','NO'),
('AFF06520','Prodotto Finito','NO'),
('AFF06520','Sartoria','NO'),
('AFF06520','Preassemblaggio','NO'),
('AFF06520','Montatori','NO'),
('AFF06520','Ufficio Acquisti','NO'),
('AFF06520','Spedizione','NO');

INSERT into PRINTHISTORY(codCodice,cpNome,propValore,STARTVALUE, ENDVALUE) value
 ('AFF06520','Officina','NO' , now() , '2099-12-31'),
('AFF06520','Prodotto Finito','NO', now() , '2099-12-31'),
('AFF06520','Sartoria','NO', now() , '2099-12-31'),
('AFF06520','Preassemblaggio','NO', now() , '2099-12-31'),
('AFF06520','Montatori','NO', now() , '2099-12-31'),
('AFF06520','Ufficio Acquisti','NO', now() , '2099-12-31'),
('AFF06520','Spedizione','NO', now() , '2099-12-31'),
('AFF06520','Spedizione','SI', now() , '2050-12-31'),
('AFF06520','Preassemblaggio','SI', now() , '2020-12-31');

/*Crea view*/
create view differentValue as
select ph.Id
from PrintPropValue ps , printhistory ph
where ps.codCodice = ph.codCodice
and ps.cpNome = ph.cpNome
and ps.propValore = ph.propValore
and ph.ENDVALUE = '2099-12-31';